/**
 * editorStateChannelWireFixtures.dom.vitest.ts — Sprint 8 Red-phase TS wire fixture tests.
 *
 * VCSDD Phase 2a (Red): This test MUST FAIL because the fixture file
 * `promptnotes/src-tauri/tests/fixtures/wire-fixtures.json` does not exist yet.
 * It is generated by the Rust test `print_wire_fixtures` in Phase 2b.
 *
 * Proof obligations verified here:
 *   PROP-IPC-011 — TS narrowing over Rust-generated fixtures (exhaustive assertNever)
 *   PROP-IPC-022 — Variant key-set equality (Set equality, NOT subset)
 *
 * After Phase 2b:
 *   1. `cargo test print_wire_fixtures` generates wire-fixtures.json
 *   2. This vitest test reads and validates it
 *
 * The test does NOT call the Rust process — it reads the JSON file synchronously.
 */

import { describe, test, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { EditingSessionStateDto } from '../../types.js';

// ── assertNever ────────────────────────────────────────────────────────────────
// Used in the default branch of switch/if-else chains to enforce exhaustive
// narrowing at the TypeScript type level. A missing case is a TS compile error.

function assertNever(x: never): never {
  throw new Error(`Unhandled discriminant: ${JSON.stringify(x)}`);
}

// ── Expected key sets per variant ─────────────────────────────────────────────
// These are canonical; any drift in the Rust DTO breaks the assertions.

const EXPECTED_KEYS = {
  idle: new Set(['status']),
  editing: new Set([
    'status',
    'currentNoteId',
    'focusedBlockId',
    'isDirty',
    'isNoteEmpty',
    'lastSaveResult',
  ]),
  editingWithBlocks: new Set([
    'status',
    'currentNoteId',
    'focusedBlockId',
    'isDirty',
    'isNoteEmpty',
    'lastSaveResult',
    'blocks',
  ]),
  saving: new Set(['status', 'currentNoteId', 'isNoteEmpty']),
  savingWithBlocks: new Set(['status', 'currentNoteId', 'isNoteEmpty', 'blocks']),
  switching: new Set(['status', 'currentNoteId', 'pendingNextFocus', 'isNoteEmpty']),
  switchingWithBlocks: new Set([
    'status',
    'currentNoteId',
    'pendingNextFocus',
    'isNoteEmpty',
    'blocks',
  ]),
  saveFailed: new Set([
    'status',
    'currentNoteId',
    'priorFocusedBlockId',
    'pendingNextFocus',
    'lastSaveError',
    'isNoteEmpty',
  ]),
  saveFailedWithBlocks: new Set([
    'status',
    'currentNoteId',
    'priorFocusedBlockId',
    'pendingNextFocus',
    'lastSaveError',
    'isNoteEmpty',
    'blocks',
  ]),
} as const;

// ── Set equality helper ────────────────────────────────────────────────────────

function setsEqual(a: Set<string>, b: Set<string>): boolean {
  if (a.size !== b.size) return false;
  for (const key of a) {
    if (!b.has(key)) return false;
  }
  return true;
}

function setDiff(actual: Set<string>, expected: Set<string>): string {
  const extra = [...actual].filter((k) => !expected.has(k));
  const missing = [...expected].filter((k) => !actual.has(k));
  return [
    extra.length ? `extra keys: [${extra.join(', ')}]` : '',
    missing.length ? `missing keys: [${missing.join(', ')}]` : '',
  ]
    .filter(Boolean)
    .join('; ');
}

// ── Fixture file path ──────────────────────────────────────────────────────────
// PROP-IPC-011: This file is generated by `cargo test print_wire_fixtures`.
// In the Red phase it does not exist; the test fails with ENOENT.

const FIXTURE_PATH = join(
  // vitest runs from the promptnotes/ directory (where package.json lives)
  process.cwd(),
  'src-tauri/tests/fixtures/wire-fixtures.json',
);

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('PROP-IPC-011 / PROP-IPC-022: wire fixture key-set and exhaustive narrowing', () => {
  // Read the fixture file once. The test will throw (Red) if the file doesn't exist.
  let fixtures: EditingSessionStateDto[];

  test('fixture file exists (generated by cargo test print_wire_fixtures)', () => {
    // This throws ENOENT in the Red phase — that IS the Red failure signal.
    const raw = readFileSync(FIXTURE_PATH, 'utf-8');
    const parsed: unknown[] = JSON.parse(raw);
    expect(Array.isArray(parsed)).toBe(true);
    expect(parsed.length).toBe(14);
    // Cast: we trust the Rust generator; the key-set tests below validate correctness.
    fixtures = parsed as EditingSessionStateDto[];
  });

  test('PROP-IPC-022: every fixture has correct key set for its variant (Set equality)', () => {
    // Re-read in case the first test populated `fixtures`.
    // If the file doesn't exist this will also throw → Red.
    const raw = readFileSync(FIXTURE_PATH, 'utf-8');
    const allFixtures: EditingSessionStateDto[] = JSON.parse(raw);

    for (const [idx, state] of allFixtures.entries()) {
      const actualKeys = new Set(Object.keys(state));
      const fixtureId = `F${String(idx + 1).padStart(2, '0')}`;

      switch (state.status) {
        case 'idle': {
          const expected = EXPECTED_KEYS.idle;
          expect(
            setsEqual(actualKeys, expected),
            `${fixtureId} idle: ${setDiff(actualKeys, expected)}`,
          ).toBe(true);
          break;
        }

        case 'editing': {
          const hasBlocks = 'blocks' in state;
          const expected = hasBlocks
            ? EXPECTED_KEYS.editingWithBlocks
            : EXPECTED_KEYS.editing;
          expect(
            setsEqual(actualKeys, expected),
            `${fixtureId} editing (blocks=${hasBlocks}): ${setDiff(actualKeys, expected)}`,
          ).toBe(true);

          // EC-IPC-007: focusedBlockId must always be present (never skip_serializing_if)
          expect(
            Object.prototype.hasOwnProperty.call(state, 'focusedBlockId'),
            `${fixtureId} editing: focusedBlockId must always be present (null or string)`,
          ).toBe(true);

          // EC-IPC-001: lastSaveResult is always present (null or "success")
          expect(
            Object.prototype.hasOwnProperty.call(state, 'lastSaveResult'),
            `${fixtureId} editing: lastSaveResult must always be present`,
          ).toBe(true);
          break;
        }

        case 'saving': {
          const hasBlocks = 'blocks' in state;
          const expected = hasBlocks
            ? EXPECTED_KEYS.savingWithBlocks
            : EXPECTED_KEYS.saving;
          expect(
            setsEqual(actualKeys, expected),
            `${fixtureId} saving (blocks=${hasBlocks}): ${setDiff(actualKeys, expected)}`,
          ).toBe(true);

          // REQ-IPC-005: these keys must NOT be present in saving
          expect(
            !Object.prototype.hasOwnProperty.call(state, 'isDirty'),
            `${fixtureId} saving: isDirty must be absent`,
          ).toBe(true);
          expect(
            !Object.prototype.hasOwnProperty.call(state, 'lastSaveResult'),
            `${fixtureId} saving: lastSaveResult must be absent`,
          ).toBe(true);
          break;
        }

        case 'switching': {
          const hasBlocks = 'blocks' in state;
          const expected = hasBlocks
            ? EXPECTED_KEYS.switchingWithBlocks
            : EXPECTED_KEYS.switching;
          expect(
            setsEqual(actualKeys, expected),
            `${fixtureId} switching (blocks=${hasBlocks}): ${setDiff(actualKeys, expected)}`,
          ).toBe(true);

          // REQ-IPC-006: pendingNextFocus must be an object {noteId, blockId}, never null
          const pnf = (state as Extract<EditingSessionStateDto, { status: 'switching' }>)
            .pendingNextFocus;
          expect(pnf).not.toBeNull();
          expect(typeof pnf).toBe('object');
          expect(typeof pnf.noteId).toBe('string');
          expect(typeof pnf.blockId).toBe('string');
          break;
        }

        case 'save-failed': {
          const hasBlocks = 'blocks' in state;
          const expected = hasBlocks
            ? EXPECTED_KEYS.saveFailedWithBlocks
            : EXPECTED_KEYS.saveFailed;
          expect(
            setsEqual(actualKeys, expected),
            `${fixtureId} save-failed (blocks=${hasBlocks}): ${setDiff(actualKeys, expected)}`,
          ).toBe(true);

          // EC-IPC-006: priorFocusedBlockId must always be present (null or string)
          expect(
            Object.prototype.hasOwnProperty.call(state, 'priorFocusedBlockId'),
            `${fixtureId} save-failed: priorFocusedBlockId must always be present`,
          ).toBe(true);

          // EC-IPC-008: pendingNextFocus must always be present (null or object)
          expect(
            Object.prototype.hasOwnProperty.call(state, 'pendingNextFocus'),
            `${fixtureId} save-failed: pendingNextFocus must always be present`,
          ).toBe(true);
          break;
        }

        default:
          // PROP-IPC-011: assertNever enforces exhaustive narrowing.
          // A new Rust variant without a TS arm is a compile error here.
          assertNever(state);
      }
    }
  });

  test('PROP-IPC-011: cover set has all 5 statuses represented', () => {
    const raw = readFileSync(FIXTURE_PATH, 'utf-8');
    const allFixtures: EditingSessionStateDto[] = JSON.parse(raw);

    const statusCounts = new Map<string, number>();
    for (const state of allFixtures) {
      statusCounts.set(state.status, (statusCounts.get(state.status) ?? 0) + 1);
    }

    // All 5 variants must appear in the cover set
    const requiredStatuses = ['idle', 'editing', 'saving', 'switching', 'save-failed'];
    for (const required of requiredStatuses) {
      expect(
        statusCounts.get(required) ?? 0,
        `Status '${required}' must appear at least once in the 14-fixture cover set`,
      ).toBeGreaterThan(0);
    }
  });

  test('PROP-IPC-011: idle fixture has exactly {"status":"idle"} (no extra fields)', () => {
    const raw = readFileSync(FIXTURE_PATH, 'utf-8');
    const allFixtures: EditingSessionStateDto[] = JSON.parse(raw);

    const idleFixtures = allFixtures.filter((f) => f.status === 'idle');
    expect(idleFixtures.length).toBe(1); // F01 only

    const idleKeys = Object.keys(idleFixtures[0]);
    expect(idleKeys).toEqual(['status']); // strict single-key check
  });
});
